version: '3'

services:
  web:
    build: .
    command: gunicorn ssc_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod.db

volumes:
  postgres_data:


# RUN
# $ docker-compose down -v
# $ docker-compose -f docker-compose.yml up -d --build

# Createsuper user
# sudo docker-compose exec web python manage.py createsuperuser
