version: '3.4'

services:
    # RabbitMQ - queue
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"

    # Django web server
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - rabbit
        depends_on:
            - rabbit
        restart: always

    # Celery worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A ConnectSW worker
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
