version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn ssc_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod.bd

volumes:
  postgres_data:
  static_volume:

# RUN
# $ docker-compose down -v
# $ docker-compose -f docker-compose.prod.yml up -d --build