version: '3.7'

services:
    # Django web server
    web: &web
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: python3 manager.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq

    # Celery worker
    worker:
        <<: *web
        build: .
        command: celery -A workerCelery worker --loglevel=info
        volumes:
            - ./app:/app
        ports: []
        depends_on:
            - rabbitmq

    #  Django app to monitor Celery status
    flower:
        hostname: flower
        image: zoomeranalytics/flower:0.9.1-4.0.2
        command: flower --address=0.0.0.0 --port=5555 --broker=amqp://admin:mypass@rabbitmq:5672/
        ports:
            - "5555:5555"
        depends_on:
            - worker

    # RabbitMQ - queue
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "15672:15672"
        expose:
            - "15672"
