version: '3.8'

services:
    # Django web server
    web:
        build: .
        command: gunicorn ConnectSW.wsgi:application -b 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - rabbitmq

    # Celery worker
    worker:
        build: .
        command: celery worker -A workerCelery --loglevel=info
        volumes:
            - .:/app
        env_file:
            - ./.env.dev
        depends_on:
            -  web
            - rabbitmq

    # Django app to monitor Celery status
    flower:
        build: .
        command: flower --address=0.0.0.0 --port=5555 --broker=amqp://localhost:5672/
        ports:
            - 5555:5555
        env_file:
            - ./.env.dev
        depends_on:
            - web
            - rabbitmq
            - worker

    # RabbitMQ - queue
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
